name: CI

# 1. When to run:
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 2. Check out your code
      - uses: actions/checkout@v3

      # 3. Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run linting (optional but recommended)
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src tests

      # 6. Run tests
      - name: Run pytest with coverage
        run: pytest --cov=src --cov-report=xml --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: |
          docker build -t rrr_ctrl:${{ github.sha }} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Tag & Push Docker image to GHCR
        run: |
          IMAGE=ghcr.io/nipundhawan/rrr_robot_control:${{ github.sha }}
          docker tag rrr_ctrl:${{ github.sha }} $IMAGE
          docker push $IMAGE


